# Generated by Django 4.2 on 2025-09-15 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0003_artisan_photo'),
        ('produits', '0002_alter_produit_options_alter_categorie_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('numero_vente', models.CharField(default='TEMP-0000', max_length=50, unique=True, verbose_name='Numéro de vente')),
                ('nom_du_client', models.CharField(blank=True, help_text='Nom du client pour la vente', max_length=100, null=True, verbose_name='Nom du client')),
                ('designation', models.CharField(blank=True, default='', help_text='Description ou référence de la vente', max_length=255, verbose_name='Désignation')),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='artisans.artisan', verbose_name='Artisan vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité vendue')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prix unitaire de vente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='produits.produit', verbose_name='Produit vendu')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente', to='ventes.vente', verbose_name='Vente associée')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'ordering': ['-id'],
            },
        ),
    ]
