# Generated by Django 4.2 on 2025-09-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE ventes_vente ADD COLUMN designation VARCHAR(255) DEFAULT '';",
            "ALTER TABLE ventes_vente DROP COLUMN designation;"
        ),
    ]

