# Generated by Django 4.2 on 2025-09-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_boutique', models.CharField(help_text="Numéro unique identifiant la boutique de l'artisan", max_length=50, unique=True, verbose_name='Numéro de boutique')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact')),
                ('adresse', models.TextField(blank=True, help_text="Adresse complète de l'artisan", null=True, verbose_name='Adresse')),
                ('specialite', models.CharField(help_text="Spécialité principale de l'artisan", max_length=100, verbose_name='Spécialité')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('actif', models.BooleanField(default=True, help_text="Désactiver pour masquer l'artisan sans supprimer ses données", verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Artisan',
                'verbose_name_plural': 'Artisans',
            },
        ),
    ]
