# Generated by Django 4.2 on 2025-09-14 20:00

import artisans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'artisan", null=True, upload_to=artisans.models.artisan_photo_path, verbose_name='Photo de profil'),
        ),
    ]
