from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, permissions
from django.db.models import Sum, Count, F
from artisans.models import Artisan
from produits.models import Produit
from ventes.models import Vente
from users.permissions import IsAdminUser, IsSecondaryAdminUser

class StatsView(APIView):
    """
    API endpoint to retrieve general statistics for the GestiArt application.
    Accessible by Admin and Secondary Admin users.

    Returns:
    - total_artisans: Total number of artisans.
    - active_products: Number of products with stock greater than 0.
    - total_sales_global: Total revenue from all sales.
    - total_revenue: Total revenue (same as total_sales_global).
    - sales_by_artisan: List of sales aggregated by artisan, ordered by total sales.
    - top_selling_products: List of top 5 selling products by quantity.
    """
    permission_classes = [IsAdminUser | IsSecondaryAdminUser]

    def get(self, request, format=None):
        """
        Handles GET requests to retrieve various statistics.
        """
        total_artisans = Artisan.objects.count()
        active_products = Produit.objects.filter(stock__gt=0).count()
        total_sales_global = Vente.objects.aggregate(total_sum=Sum(F('quantity') * F('unit_price')))['total_sum'] or 0
        total_revenue = total_sales_global

        sales_by_artisan = Vente.objects.values('artisan__first_name', 'artisan__last_name')\
                                       .annotate(total_sales=Sum(F('quantity') * F('unit_price')))\
                                       .order_by('-total_sales')

        top_selling_products = Vente.objects.values('product__name')\
                                        .annotate(total_quantity_sold=Sum('quantity'))\
                                        .order_by('-total_quantity_sold')[:5]

        data = {
            'total_artisans': total_artisans,
            'active_products': active_products,
            'total_sales_global': total_sales_global,
            'total_revenue': total_revenue,
            'sales_by_artisan': list(sales_by_artisan),
            'top_selling_products': list(top_selling_products),
        }
        return Response(data, status=status.HTTP_200_OK)

class ReportCardView(APIView):
    """
    API endpoint to generate a tabular report card for all artisans, their products, and sales.
    Accessible by Admin and Secondary Admin users.

    Returns a list of dictionaries, where each dictionary represents a row in the report table.
    Each row contains:
    - artisan_name: Full name of the artisan.
    - speciality: Artisan's speciality.
    - product_name: Name of the product.
    - product_category: Category of the product.
    - product_price: Price of the product.
    - product_stock: Current stock of the product.
    - total_sales_for_product: Total quantity sold for this product.
    - revenue_for_product: Total revenue generated by this product.
    """
    permission_classes = [IsAdminUser | IsSecondaryAdminUser]

    def get(self, request, format=None):
        """
        Handles GET requests to generate the report card.
        """
        report_data = []
        artisans = Artisan.objects.all()

        for artisan in artisans:
            products = Produit.objects.filter(artisan=artisan)
            if not products.exists():
                report_data.append({
                    'artisan_name': f'{artisan.first_name} {artisan.last_name}',
                    'speciality': artisan.speciality,
                    'product_name': 'N/A',
                    'product_category': 'N/A',
                    'product_price': 0,
                    'product_stock': 0,
                    'total_sales_for_product': 0,
                    'revenue_for_product': 0,
                })
                continue

            for product in products:
                sales_for_product = Vente.objects.filter(product=product)
                total_quantity_sold = sales_for_product.aggregate(Sum('quantity'))['quantity__sum'] or 0
                revenue_for_product = sales_for_product.aggregate(total_revenue=Sum(F('quantity') * F('unit_price')))['total_revenue'] or 0

                report_data.append({
                    'artisan_name': f'{artisan.first_name} {artisan.last_name}',
                    'speciality': artisan.speciality,
                    'product_name': product.name,
                    'product_category': product.category,
                    'product_price': product.price,
                    'product_stock': product.stock,
                    'total_sales_for_product': total_quantity_sold,
                    'revenue_for_product': revenue_for_product,
                })
        
        return Response(report_data, status=status.HTTP_200_OK)
