# Generated by Django 4.2 on 2025-09-06 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits_images/')),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='artisans.artisan')),
            ],
        ),
    ]
