# Generated by Django 4.2 on 2025-09-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="categories.category",
            ),
        ),
    ]
