# Generated by Django 4.2 on 2025-09-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_categorie_remove_produit_category_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='numero_boutique',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de boutique'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Quantité en stock'),
        ),
    ]
